name: Pylon
services:
  app:
    image: linuxserver/pylon@sha256:adcb6dc14c0516c0dbb51d332b51ccf89ea83f35ed953ff2093818cc0ed2963d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      GITURL: ''
      PYUSER: ''
      PYPASS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: GITURL
          description:
            en_us: Specify a git repo to checkout on first startup
        - container: PYUSER
          description:
            en_us: Specify a basic auth user.
        - container: PYPASS
          description:
            en_us: Specify a basic auth password.
      volumes:
        - container: /code
          description:
            en_us: if you want to mount up a local folder of code instead of checking out a Git URL specify its location here.  Find it at /code
      ports:
        - container: 3131
          description:
            en_us: Webui - Default 3131
    ports:
      - target: 3131
        published: 3131
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pylon/config
        target: /config
      - type: bind
        source: /DATA/AppData/pylon/code
        target: /code
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/pylon/'
  tagline:
    en_us: A web based integrated development environment built with Node.js as a backend and with a supercharged JavaScript/HTML5 frontend, licensed under GPL version 3. This project originates from Cloud9 v2 project.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cloud9-logo.png
  thumbnail: https://raw.githubusercontent.com/pylonide/pylon/master/doc/screenshot02.png
  title:
    en_us: Pylon
  port_map: '3131'
