name: LinuxServer-Nntp2nntp
services:
  app:
    image: linuxserver/nntp2nntp:0.3.20221013
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: PUID
          description:
            en_us: specify your UID
        - container: PGID
          description:
            en_us: specify your GID
      volumes:
        - container: /config
          description:
            en_us: appdata
      ports:
        - container: '1563'
          description:
            en_us: Proxy Port
    ports:
      - target: 1563
        published: 1563
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nntp2nntp/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/nntp2nntp/'
  tagline:
    en_us: 'Proxy Allow You To Use Your Nntp Account From Multiple Systems, Each With Own User Name And Password. It Fully Supports Ssl And You Can Also Limit The Access To Proxy With Ssl Certificates. Nntp2nntp Proxy Is Very Simple And Pretty Fast. ## Warning Whilst We Know Of No Nntp2nntp Security Issues The upstream Code For This Project Has Received No Changes Since 06.08.15 And Is Likely Abandoned Permanently. For This Reason We Strongly Recommend You Do Not Make This Application Public Facing And If You Must Do So Other Layers Of Security And Ssl Should Be Considered An Absolute Bare Minimum Requirement. We See This Proxy Being Used Primarily On A Lan So That All The Users Nntp Applications Can Share A Common Set Of Internal Credentials Allowing For Central Managment Of The Upstream Account E.g Change Provider, Server, Thread Limits For All Applications With One Global Config Change.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nntp2nntp.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nntp2nntp.png
  title:
    en_us: Nntp2nntp
  category: LinuxServer.io
