name: LinuxServer-Grocy
services:
  app:
    image: linuxserver/grocy:3.3.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '9283'
          description:
            en_us: Webui Port
    ports:
      - target: 9283
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/grocy/'
  tagline:
    en_us: 'An Erp System For Your Kitchen! Cut Down On Food Waste, And Manage Your Chores With This Brilliant Utility. Keep Track Of Your Purchases, How Much Food You Are Wasting, What Chores Need Doing And What Batteries Need Charging With This Proudly Open Source Tool For More Information On Grocy Visit Their Website And Check It Out: Https://grocy.info'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grocy-icon.png
  thumbnail: https://grocy.info/img/grocy_logo.svg
  title:
    en_us: Grocy
  category: LinuxServer.io
  port_map: '80'
