name: Requestrr
services:
  app:
    image: linuxserver/requestrr@undefined
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Contains all relevant configuration files.
      ports:
        - container: '4545'
          description:
            en_us: web gui
    ports:
      - target: 4545
        published: 4545
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/requestrr/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
  tagline:
    en_us: A chatbot used to simplify using services like Sonarr/Radarr/Ombi via the use of chat.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/requestrr.png
  thumbnail: https://github.com/darkalfx/requestrr/raw/master/Logos/requestrr_discord_Icon_512.png
  title:
    en_us: Requestrr
  category: Media
  port_map: '4545'
