name: LinuxServer-Plex
services:
  app:
    image: linuxserver/plex:1.32.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VERSION: ''
      PLEX_CLAIM: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: VERSION
          description:
            en_us: Set whether to update plex or not - see Application Setup section.
        - container: PLEX_CLAIM
          description:
            en_us: Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
      volumes:
        - container: /config
          description:
            en_us: Appdata
        - container: /tv
          description:
            en_us: TV - /tv
        - container: /movies
          description:
            en_us: Movies - /movies
      ports:
        - container: '32400'
          description:
            en_us: For access to the Plex Media Server Webui (No effect in host mode - reference only)
        - container: '3005'
          description:
            en_us: For controlling Plex Home Theater via Plex Companion (No effect in host mode - reference only)
        - container: '8324'
          description:
            en_us: For controlling Plex for Roku via Plex Companion (No effect in host mode - reference only)
        - container: '32469'
          description:
            en_us: For access to the Plex DLNA Server (No effect in host mode - reference only)
        - container: '1900'
          description:
            en_us: For access to the Plex DLNA Server (No effect in host mode - reference only)
        - container: '32410'
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: '32412'
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: '32413'
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: '32414'
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
    volumes:
      - type: bind
        source: /DATA/AppData/plex/config
        target: /config
      - type: bind
        source: /DATA/AppData/plex/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/plex/movies
        target: /movies
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
      - target: 3005
        published: 3005
        protocol: tcp
      - target: 8324
        published: 8324
        protocol: tcp
      - target: 32469
        published: 32469
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
      - target: 32410
        published: 32410
        protocol: udp
      - target: 32412
        published: 32412
        protocol: udp
      - target: 32413
        published: 32413
        protocol: udp
      - target: 32414
        published: 32414
        protocol: udp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/plex/'
  tagline:
    en_us: Organizes Video, Music And Photos From Personal Media Libraries And Streams Them To Smart Tvs, Streaming Boxes And Mobile Devices. This Container Is Packaged As A Standalone Plex Media Server. Has Always Been A Top Priority. Straightforward Design And Bulk Actions Mean Getting Things Done Faster.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-icon.png
  thumbnail: http://the-gadgeteer.com/wp-content/uploads/2015/10/plex-logo-e1446990678679.png
  title:
    en_us: Plex
  category: LinuxServer.io
  port_map: '32400'
  index: /web
