name: LinuxServer-Foldingathome
services:
  app:
    image: linuxserver/foldingathome:7.6.21
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '7396'
          description:
            en_us: GUI Port - Default 7396
        - container: '36330'
          description:
            en_us: FAHControl Port - Default 36330
    ports:
      - target: 7396
        published: 7396
        protocol: tcp
      - target: 36330
        published: 36330
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/foldingathome/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/foldingathome/'
  tagline:
    en_us: A Distributed Computing Project For Simulating Protein Dynamics, Including The Process Of Protein Folding And The Movements Of Proteins Implicated In A Variety Of Diseases. It Brings Together Citizen Scientists Who Volunteer To Run Simulations Of Protein Dynamics On Their Personal Computers. Insights From This Data Are Helping Scientists To Better Understand Biology, And Providing New Opportunities For Developing Therapeutics.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/foldingathome-logo.png
  thumbnail: https://foldingathome.org/wp-content/uploads/2016/09/folding-at-home-logo.png
  title:
    en_us: Foldingathome
  category: LinuxServer.io
  port_map: '7396'
