name: Sickchill
services:
  app:
    image: linuxserver/sickchill@sha256:7f95c672e983d403c228274bdd5e700b2ea30fcb25f3ac271c82e4456abb5007
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /downloads
          description:
            en_us: 'Container Path: /downloads'
        - container: /tv
          description:
            en_us: 'Container Path: /tv'
      ports:
        - container: '8081'
          description:
            en_us: 'Container Port: 8081'
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sickchill/config
        target: /config
      - type: bind
        source: /DATA/AppData/sickchill/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/sickchill/tv
        target: /tv
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/sickchill/'
  tagline:
    en_us: An Automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sickchill-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sickchill-banner.png
  title:
    en_us: Sickchill
  port_map: '8081'
