name: LinuxServer-Jackett
services:
  app:
    image: linuxserver/jackett:0.21.157-development
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      AUTO_UPDATE: ''
      RUN_OPTS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: AUTO_UPDATE
          description:
            en_us: Allow Jackett to update inside of the container (currently recommended by Jackett and enabled by default)
        - container: RUN_OPTS
          description:
            en_us: Optionally specify additional arguments to be passed.
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/jackett/config
        target: /config
      - type: bind
        source: /DATA/AppData/jackett/downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/jackett/'
  tagline:
    en_us: 'Works As A Proxy Server: It Translates Queries From Apps (sonarr, Sickrage, Couchpotato, Mylar, Etc) Into Tracker-site-specific Http Queries, Parses The Html Response, Then Sends Results Back To The Requesting Software. This Allows For Getting Recent Uploads (like Rss) And Performing Searches. Jackett Is A Single Repository Of Maintained Indexer Scraping & Translation Logic - Removing The Burden From Other Apps.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jacket-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
  title:
    en_us: Jackett
  category: LinuxServer.io
  port_map: '9117'
