name: LinuxServer-Jellyfin
services:
  app:
    image: linuxserver/jellyfin:10.8.10
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      JELLYFIN_PublishedServerUrl: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: JELLYFIN_PublishedServerUrl
          description:
            en_us: Set the autodiscovery response domain or IP address.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '8096'
          description:
            en_us: Webui - Default 8096 (HTTP)
        - container: '8920'
          description:
            en_us: Webui - Default 8920 (HTTPS) (Optional)
        - container: '1900'
          description:
            en_us: Service Discovery (Optional)
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
      - target: 8920
        published: 8920
        protocol: tcp
      - target: 7359
        published: 7359
        protocol: udp
      - target: 1900
        published: 1900
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/AppData/jellyfin/data/tvshows
        target: /data/tvshows
      - type: bind
        source: /DATA/AppData/jellyfin/data/movies
        target: /data/movies
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/jellyfin/'
  tagline:
    en_us: 'A Free Software Media System That Puts You In Control Of Managing And Streaming Your Media. It Is An Alternative To The Proprietary Emby And Plex, To Provide Media From A Dedicated Server To End-user Devices Via Multiple Apps. Jellyfin Is Descended From Emby''s 3.5.2 Release And Ported To The .net Core Framework To Enable Full Cross-platform Support. There Are No Strings Attached, No Premium Licenses Or Features, And No Hidden Agendas: Just A Team Who Want To Build Something Better And Work Together To Achieve It.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  thumbnail: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/banner-logo-solid.svg?sanitize=true
  title:
    en_us: Jellyfin
  category: LinuxServer.io
  port_map: '8096'
