name: Pydio-cells
services:
  app:
    image: linuxserver/pydio-cells@sha256:ceb00d1dd836099180a212f6b4830182aef7bfadcecc65d25078ccfee85288fd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: EXTERNALURL
          description:
            en_us: The external url you would like to use to access Pydio Cells (Can be https://domain.url or https://IP:PORT).
        - container: SERVER_IP
          description:
            en_us: Enter the LAN IP of the docker server. Required for local access by IP, added to self signed cert as SAN (not required if accessing only through reverse proxy).
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: 8080
          description:
            en_us: 'Container Port: 8080'
        - container: 33060
          description:
            en_us: 'Container Port: 33060'
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 33060
        published: 33060
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/pydio-cells/'
  tagline:
    en_us: The nextgen file sharing platform for organizations. It is a full rewrite of the Pydio project using the Go language following a micro-service architecture.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/pydio-cells-icon.png
  thumbnail: https://raw.githubusercontent.com/wiki/pydio/cells/images/PydioCellsColor.png
  title:
    en_us: Pydio-cells
  port_map: '8080'
