name: LinuxServer-Pydio-cells
services:
  app:
    image: linuxserver/pydio-cells:4.2.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: EXTERNALURL
          description:
            en_us: The external url you would like to use to access Pydio Cells (Can be https://domain.url or https://IP:PORT).
        - container: SERVER_IP
          description:
            en_us: Enter the LAN IP of the docker server. Required for local access by IP, added to self signed cert as SAN (not required if accessing only through reverse proxy).
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
        - container: '33060'
          description:
            en_us: 'Container Port: 33060'
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 33060
        published: 33060
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/pydio-cells/'
  tagline:
    en_us: The Nextgen File Sharing Platform For Organizations. It Is A Full Rewrite Of The Pydio Project Using The Go Language Following A Micro-service Architecture.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/pydio-cells-icon.png
  thumbnail: https://raw.githubusercontent.com/wiki/pydio/cells/images/PydioCellsColor.png
  title:
    en_us: Pydio Cells
  category: LinuxServer.io
  port_map: '8080'
