name: LinuxServer-Calibre-web
services:
  app:
    image: linuxserver/calibre-web:0.6.20
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
      OAUTHLIB_RELAX_TOKEN_SCOPE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DOCKER_MODS
          description:
            en_us: '#optional & x86-64 only Adds the ability to perform ebook conversion'
        - container: OAUTHLIB_RELAX_TOKEN_SCOPE
          description:
            en_us: Optionally set this to allow Google OAUTH to work
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /books
          description:
            en_us: Location of Calibre library
      ports:
        - container: '8083'
          description:
            en_us: Webui - Default 8083
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre-web/config
        target: /config
      - type: bind
        source: /DATA/AppData/calibre-web/books
        target: /books
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/calibre-web/'
  tagline:
    en_us: A Web App Providing A Clean Interface For Browsing, Reading And Downloading Ebooks Using An Existing Calibre Database. It Is Also Possible To Integrate Google Drive And Edit Metadata And Your Calibre Library Through The App Itself. This Software Is A Fork Of Library And Licensed Under The Gpl V3 License.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
  title:
    en_us: Calibre Web
  category: LinuxServer.io
  port_map: '8083'
