name: LinuxServer-Mstream
services:
  app:
    image: linuxserver/mstream:5.11.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
        - container: /music
          description:
            en_us: Path to music library
      ports:
        - container: '3000'
          description:
            en_us: Webui Port
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mstream/config
        target: /config
      - type: bind
        source: /DATA/AppData/mstream/music
        target: /music
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/mstream/'
  tagline:
    en_us: A Personal Music Streaming Server. You Can Use Mstream To Stream Your Music From Your Home Computer To Any Device, Anywhere. There Are Mobile Apps Available For Both Android And Iphone.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mstream-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mstream-icon.png
  title:
    en_us: Mstream
  category: LinuxServer.io
  port_map: '3000'
