name: Fail2ban
services:
  app:
    image: linuxserver/fail2ban@sha256:38c37fac90a0b64e0261a35ecfd8ee326b86ce1c113be3384d75f3e0615c07db
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/fail2ban/config
        target: /config
      - type: bind
        source: /DATA/AppData/fail2ban/var/log:ro
        target: /var/log:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/airsonic:ro
        target: /remotelogs/airsonic:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/apache2:ro
        target: /remotelogs/apache2:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/authelia:ro
        target: /remotelogs/authelia:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/emby:ro
        target: /remotelogs/emby:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/filebrowser:ro
        target: /remotelogs/filebrowser:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/homeassistant:ro
        target: /remotelogs/homeassistant:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/lighttpd:ro
        target: /remotelogs/lighttpd:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nextcloud:ro
        target: /remotelogs/nextcloud:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nginx:ro
        target: /remotelogs/nginx:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nzbget:ro
        target: /remotelogs/nzbget:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/overseerr:ro
        target: /remotelogs/overseerr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/prowlarr:ro
        target: /remotelogs/prowlarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/radarr:ro
        target: /remotelogs/radarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/sabnzbd:ro
        target: /remotelogs/sabnzbd:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/sonarr:ro
        target: /remotelogs/sonarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/unificontroller:ro
        target: /remotelogs/unificontroller:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/vaultwarden:ro
        target: /remotelogs/vaultwarden:ro
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Fail2ban is a daemon to ban hosts that cause multiple authentication errors.
  tagline:
    en_us: A daemon to ban hosts that cause multiple authentication errors.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
  title:
    en_us: Fail2ban
  port_map: '80'
