name: LinuxServer-Lidarr
services:
  app:
    image: linuxserver/lidarr:1.1.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 8686
        published: 8686
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lidarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/lidarr/music
        target: /music
      - type: bind
        source: /DATA/AppData/lidarr/downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/lidarr/'
  tagline:
    en_us: A Music Collection Manager For Usenet And Bittorrent Users. It Can Monitor Multiple Rss Feeds For New Tracks From Your Favorite Artists And Will Grab, Sort And Rename Them. It Can Also Be Configured To Automatically Upgrade The Quality Of Files Already Downloaded When A Better Quality Format Becomes Available.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr.png
  thumbnail: https://github.com/lidarr/Lidarr/raw/develop/Logo/400.png
  title:
    en_us: Lidarr
  category: LinuxServer.io
  port_map: '8686'
