name: LinuxServer-Nextcloud
services:
  app:
    image: linuxserver/nextcloud:27.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/config
        target: /config
      - type: bind
        source: /DATA/AppData/nextcloud/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/nextcloud'
  tagline:
    en_us: Gives You Access To All Your Files Wherever You Are. Where Are Your Photos And Documents? With Nextcloud You Pick A Server Of Your Choice, At Home, In A Data Center Or At A Provider. And That Is Where Your Files Will Be. Nextcloud Runs On That Server, Protecting Your Data And Giving You Access From Your Desktop Or Mobile Devices. Through Nextcloud You Also Access, Sync And Share Your Existing Data On That Ftp Drive At The Office, A Dropbox Or A Nas You Have At Home.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-icon.png
  title:
    en_us: Nextcloud
  category: LinuxServer.io
  port_map: '80'
