name: LinuxServer-Ngircd
services:
  app:
    image: linuxserver/ngircd:version-26.1-r3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '6667'
          description:
            en_us: 'Container Port: 6667'
    ports:
      - target: 6667
        published: 6667
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ngircd/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/ngircd/'
  tagline:
    en_us: A Free, Portable And Lightweight Internet Relay Chat Server For Small Or Private Networks, Developed Under The Gnu General Public License (gpl). It Is Easy To Configure, Can Cope With Dynamic Ip Addresses, And Supports Ipv6, Ssl-protected Connections As Well As Pam For Authentication. It Is Written From Scratch And Not Based On The Original Ircd.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ngircd-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ngircd-logo.png
  title:
    en_us: Ngircd
  category: LinuxServer.io
  port_map: '6667'
