name: LinuxServer-Ci
services:
  app:
    image: linuxserver/ci:version-da63cc62
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ci/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/ci for details.
  tagline:
    en_us: This Container Needs Special Attention. Please Check Https://hub.docker.com/r/linuxserver/ci For Details.
  developer: LinuxServer.io
  author: WisdomSky
  icon: ''
  thumbnail: ''
  title:
    en_us: Ci
  category: LinuxServer.io
  port_map: '80'
