name: Budge
services:
  app:
    image: linuxserver/budge@sha256:f83866215d2dd533d32d4f90cbb941c49c70177f3578cdf67085820b2cc5cf49
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/budge/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Budge is an open source 'budgeting with envelopes' personal finance app.
  tagline:
    en_us: An open source 'budgeting with envelopes' personal finance app.
  developer: LinuxServer.io
  author: WisdomSky
  icon: ''
  thumbnail: ''
  title:
    en_us: Budge
  port_map: '80'
