name: LinuxServer-Prowlarr
services:
  app:
    image: linuxserver/prowlarr:1.6.0-nightly
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Database and Prowlarr configs
      ports:
        - container: '9696'
          description:
            en_us: The port for the Prowlarr webinterface
    ports:
      - target: 9696
        published: 9696
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/prowlarr/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/prowlarr'
  tagline:
    en_us: A Indexer Manager/proxy Built On The Popular Arr .net/reactjs Base Stack To Integrate With Your Various Pvr Apps. Prowlarr Supports Both Torrent Trackers And Usenet Indexers. It Integrates Seamlessly With Sonarr, Radarr, Lidarr, And Readarr Offering Complete Management Of Your Indexers With No Per App Indexer Setup Required (we Do It All).
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png
  title:
    en_us: Prowlarr
  category: LinuxServer.io
  port_map: '9696'
