name: LinuxServer-Rsnapshot
services:
  app:
    image: linuxserver/rsnapshot:1.4.5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
        - container: /.snapshots
          description:
            en_us: Snapshots
        - container: /data
          description:
            en_us: Data
      ports: []
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/rsnapshot/'
  tagline:
    en_us: A Filesystem Snapshot Utility Based On Rsync. Rsnapshot Makes It Easy To Make Periodic Snapshots Of Local Machines, And Remote Machines Over Ssh. The Code Makes Extensive Use Of Hard Links Whenever Possible, To Greatly Reduce The Disk Space Required.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rsnapshot.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rsnapshot.png
  title:
    en_us: Rsnapshot
  category: LinuxServer.io
  port_map: '80'
