name: LinuxServer-Hishtory-server
services:
  app:
    image: linuxserver/hishtory-server:0.208.20230623
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HISHTORY_POSTGRES_DB: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: HISHTORY_POSTGRES_DB
          description:
            en_us: Postgres DB Connection URI. Special characters must be URL encoded.
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: hiSHtory is a better shell history. It stores your shell history in context (what directory you ran the command in, whether it succeeded or failed, how long it took, etc). This is all stored locally and end-to-end encrypted for syncing to to all your other computers.
  tagline:
    en_us: A Better Shell History. It Stores Your Shell History In Context (what Directory You Ran The Command In, Whether It Succeeded Or Failed, How Long It Took, Etc). This Is All Stored Locally And End-to-end Encrypted For Syncing To To All Your Other Computers.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hishtory-server-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hishtory-server-icon.png
  title:
    en_us: Hishtory Server
  category: LinuxServer.io
  port_map: '8080'
