name: LinuxServer-Endlessh
services:
  app:
    image: linuxserver/endlessh:version-dfe44eb2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MSDELAY: ''
      MAXLINES: ''
      MAXCLIENTS: ''
      LOGFILE: ''
      BINDFAMILY: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MSDELAY
          description:
            en_us: The endless banner is sent one line at a time. This is the delay in milliseconds between individual lines.
        - container: MAXLINES
          description:
            en_us: The length of each line is randomized. This controls the maximum length of each line. Shorter lines may keep clients on for longer if they give up after a certain number of bytes.
        - container: MAXCLIENTS
          description:
            en_us: Maximum number of connections to accept at a time. Connections beyond this are not immediately rejected, but will wait in the queue.
        - container: LOGFILE
          description:
            en_us: By default, the app logs to container log. If this is set to true, the log will be output to file under /config/logs/endlessh (/config needs to be mapped).
        - container: BINDFAMILY
          description:
            en_us: By default, the app binds to IPv4 and IPv6 addresses. Set it to 4 or 6 to bind to IPv4 only or IPv6 only, respectively. Leave blank to bind to both.
      volumes:
        - container: /config
          description:
            en_us: Required if `LOGFILE` is set to `true`.
      ports:
        - container: '22'
          description:
            en_us: ssh port
    ports:
      - target: 22
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/endlessh/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
  tagline:
    en_us: An Ssh Tarpit That Very Slowly Sends An Endless, Random Ssh Banner. It Keeps Ssh Clients Locked Up For Hours Or Even Days At A Time. The Purpose Is To Put Your Real Ssh Server On Another Port And Then Let The Script Kiddies Get Stuck In This Tarpit Instead Of Bothering A Real Server.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  title:
    en_us: Endlessh
  category: LinuxServer.io
  port_map: '8080'
