name: LinuxServer-Lychee
services:
  app:
    image: linuxserver/lychee:4.9.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DB_HOST
          description:
            en_us: for specifying the database host
        - container: DB_PORT
          description:
            en_us: for specifying the database port
        - container: DB_USERNAME
          description:
            en_us: for specifying the database user
        - container: DB_PASSWORD
          description:
            en_us: for specifying the database password
        - container: DB_DATABASE
          description:
            en_us: for specifying the database to be used
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /pictures
          description:
            en_us: 'Container Path: /pictures'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lychee/config
        target: /config
      - type: bind
        source: /DATA/AppData/lychee/pictures
        target: /pictures
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/lychee/'
  tagline:
    en_us: 'A Free Photo-management Tool, Which Runs On Your Server Or Web-space. Installing Is A Matter Of Seconds. Upload, Manage And Share Photos Like From A Native Application. Lychee Comes With Everything You Need And All Your Photos Are Stored Securely.'' ### Upgrade Warning Please Note That The V4 Upgrade Process Resets All Password-protected Albums. Any Albums That Were Made Public With A Password Will Need To Be Re-secured.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lychee-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lychee-icon.png
  title:
    en_us: Lychee
  category: LinuxServer.io
  port_map: '80'
