name: LinuxServer-Cops
services:
  app:
    image: linuxserver/cops:1.1.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cops/config
        target: /config
      - type: bind
        source: /DATA/AppData/cops/books
        target: /books
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/cops/'
  tagline:
    en_us: 'By Sébastien Lucas, Stands For Calibre Opds (and Html) Php Server. Cops Links To Your Calibre Library Database And Allows Downloading And Emailing Of Books Directly From A Web Browser And Provides A Opds Feed To Connect To Your Devices. Changes In Your Calibre Library Are Reflected Immediately In Your Cops Pages. See : cops''s Home For More Details. Don''t Forget To Check The wiki. ## Why? (taken From The Author''s Site) In My Opinion Calibre Is A Marvelous Tool But Is Too Big And Has Too Much Dependencies To Be Used For Its Content Server. That''s The Main Reason Why I Coded This Opds Server. I Needed A Simple Tool To Be Installed On A Small Server (seagate Dockstar In My Case). I Initially Thought Of Calibre2opds But As It Generate Static File No Search Was Possible. Later I Added An Simple Html Catalog That Should Be Usable On My Kobo. So Cops''s Main Advantages Are : * No Need For Many Dependencies. * No Need For A Lot Of Cpu Or Ram. * Not Much Code. * Search Is Available. * With Dropbox / Owncloud It''s Very Easy To Have An Up To Date Opds Server. * It Was Fun To Code. If You Want To Use The Opds Feed Don''t Forget To Specify Feed.php At The End Of Your Url.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cops-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cops-icon.png
  title:
    en_us: Cops
  category: LinuxServer.io
  port_map: '80'
