name: linuxserver-synclounge
services:
  app:
    image: linuxserver/synclounge:5.2.24
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
      AUTOJOIN_ENABLED: ''
      AUTOJOIN_ROOM: ''
    x-casaos:
      envs:
        - container: AUTH_LIST
          description:
            en_us: If set, only the users defined here and the users of the plex servers defined here will be able to access the server. Use e-mails, plex usernames and/or plex server machine ids, comma separated, no spaces.
        - container: AUTOJOIN_ENABLED
          description:
            en_us: DEPRECATED - (Still works but will be removed in the future in favor of the built-in var autojoin__room) - Set to true to let users autojoin the server and a room (specified by the AUTOJOIN_ROOM var).
        - container: AUTOJOIN_ROOM
          description:
            en_us: DEPRECATED - (Still works but will be removed in the future in favor of the built-in var autojoin__room) - Set the room name for auto joining (requires AUTOJOIN_ENABLED set to true).
      ports:
        - container: '8088'
          description:
            en_us: 'Container Port: 8088'
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/synclounge/'
  tagline:
    en_us: A third party tool that allows you to watch Plex in sync with your friends/family, wherever you are.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/synclounge-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/synclounge-banner.png
  title:
    en_us: Synclounge
  category: LinuxServer.io
  project_url: https://github.com/samcm/synclounge
  port_map: '8088'
