name: LinuxServer-Tvheadend
services:
  app:
    image: linuxserver/tvheadend:version-7b5c5269
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: RUN_OPTS
          description:
            en_us: Optionally specify additional arguments to be passed. See Additional runtime parameters.
      volumes:
        - container: /config
          description:
            en_us: Config
        - container: /recordings
          description:
            en_us: Recordings
      ports:
        - container: '9981'
          description:
            en_us: Webgui
        - container: '9982'
          description:
            en_us: HTSP
    ports:
      - target: 9981
        published: 9981
        protocol: tcp
      - target: 9982
        published: 9982
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tvheadend/config
        target: /config
      - type: bind
        source: /DATA/AppData/tvheadend/recordings
        target: /recordings
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/tvheadend/'
  tagline:
    en_us: 'Works As A Proxy Server: Is A Tv Streaming Server And Recorder For Linux, Freebsd And Android Supporting Dvb-s, Dvb-s2, Dvb-c, Dvb-t, Atsc, Isdb-t, Iptv, Sat>ip And Hdhomerun As Input Sources. Tvheadend Offers The Http (vlc, Mplayer), Htsp (kodi, Movian) And Sat>ip Streaming. Multiple Epg Sources Are Supported (over-the-air Dvb And Atsc Including Opentv Dvb Extensions, Xmltv, Pyxml).'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tvheadend-big.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tvheadend-big.png
  title:
    en_us: Tvheadend
  category: LinuxServer.io
  port_map: '9981'
