name: Raneto
services:
  app:
    image: linuxserver/raneto@sha256:62443a6bc91081b39961d349a5b021d21bd9178b14ac45735243b7557bc8cf04
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '3000'
          description:
            en_us: Webui - Default port 3000
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/raneto/'
  tagline:
    en_us: is an open source Knowledgebase platform that uses static Markdown files to power your Knowledgebase.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/raneto.png
  thumbnail: https://raw.githubusercontent.com/gilbitron/Raneto/master/logo/logo_readme.png
  title:
    en_us: Raneto
  port_map: '3000'
