name: LinuxServer-Davos
services:
  app:
    image: linuxserver/davos:2.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /download
          description:
            en_us: 'Container Path: /download'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/davos/config
        target: /config
      - type: bind
        source: /DATA/AppData/davos/download
        target: /download
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/davos/'
  tagline:
    en_us: An Ftp Automation Tool That Periodically Scans Given Host Locations For New Files. It Can Be Configured For Various Purposes, Including Listening For Specific Files To Appear In The Host Location, Ready For It To Download And Then Move, If Required. It Also Supports Completion Notifications As Well As Downstream Api Calls, To Further The Workflow.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/davos.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/davos/master/docs/list.PNG
  title:
    en_us: Davos
  category: LinuxServer.io
  port_map: '8080'
