name: LinuxServer-Bookstack
services:
  app:
    image: linuxserver/bookstack:23.05.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_URL: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USER: ''
      DB_PASS: ''
      DB_DATABASE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: APP_URL
          description:
            en_us: for specifying the IP:port or URL your application will be accessed on (ie. http://192.168.1.1:6875 or https://bookstack.mydomain.com
        - container: DB_HOST
          description:
            en_us: for specifying the database host
        - container: DB_PORT
          description:
            en_us: for specifying the database port if not default 3306
        - container: DB_USER
          description:
            en_us: for specifying the database user
        - container: DB_PASS
          description:
            en_us: for specifying the database password (non-alphanumeric passwords must be properly escaped.)
        - container: DB_DATABASE
          description:
            en_us: for specifying the database to be used
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '6875'
          description:
            en_us: 'Container Port: 80'
    ports:
      - target: 6875
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bookstack/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/bookstack'
  tagline:
    en_us: 'A Free And Open Source Wiki Designed For Creating Beautiful Documentation. Featuring A Simple, But Powerful Wysiwyg Editor It Allows For Teams To Create Detailed And Useful Documentation With Ease. Powered By Sql And Including A Markdown Editor For Those Who Prefer It, Bookstack Is Geared Towards Making Documentation More Of A Pleasure Than A Chore. For More Information On Bookstack Visit Their Website And Check It Out: Https://www.bookstackapp.com'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://camo.githubusercontent.com/bc396d418b9da24e78f541bf221d8cc64b47c033/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f6c696e75787365727665722d646f63732f696d616765732f626f6f6b737461636b2d6c6f676f353030783530302e706e67
  thumbnail: https://s3-us-west-2.amazonaws.com/linuxserver-docs/images/bookstack-logo500x500.png
  title:
    en_us: Bookstack
  category: LinuxServer.io
  port_map: '80'
