name: LinuxServer-Remmina
services:
  app:
    image: linuxserver/remmina:1.4.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/remmina/'
  tagline:
    en_us: A Remote Desktop Client Written In Gtk, Aiming To Be Useful For System Administrators And Travellers, Who Need To Work With Lots Of Remote Computers In Front Of Either Large Or Tiny Screens. Remmina Supports Multiple Network Protocols, In An Integrated And Consistent User Interface. Currently Rdp, Vnc, Spice, Nx, Xdmcp, Ssh And Exec Are Supported.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/remmina-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/remmina-icon.png
  title:
    en_us: Remmina
  category: LinuxServer.io
  port_map: '3000'
