name: LinuxServer-Projectsend
services:
  app:
    image: linuxserver/projectsend:version-r1605
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MAX_UPLOAD: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MAX_UPLOAD
          description:
            en_us: To set maximum upload size (in MB), default if unset is 5000.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/projectsend/config
        target: /config
      - type: bind
        source: /DATA/AppData/projectsend/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/projectsend/'
  tagline:
    en_us: A Self-hosted Application That Lets You Upload Files And Assign Them To Specific Clients That You Create Yourself. Secure, Private And Easy. No More Depending On External Services Or E-mail To Send Those Files.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/projectsend-logo.png
  thumbnail: http://www.projectsend.org/wp-content/themes/projectsend/img/screenshots.png
  title:
    en_us: Projectsend
  category: LinuxServer.io
  port_map: '80'
