name: LinuxServer-Quassel-web
services:
  app:
    image: linuxserver/quassel-web:version-20880f2c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      QUASSEL_CORE: ''
      QUASSEL_PORT: ''
      URL_BASE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: QUASSEL_CORE
          description:
            en_us: specify the URL or IP address of your Quassel Core instance
        - container: QUASSEL_PORT
          description:
            en_us: specify the port of your Quassel Core instance
        - container: URL_BASE
          description:
            en_us: Specify a url-base in reverse proxy setups ie. /quassel
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports: []
    ports:
      - target: 64443
        published: 64443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/quassel-web/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/quassel-web/'
  tagline:
    en_us: A Web Client For Quassel. Note That A Quassel-core Instance Is Required, We Have A Container Available here.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/quassel-web-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/quassel-web-banner.png
  title:
    en_us: Quassel Web
  category: LinuxServer.io
  port_map: '64080'
