name: LinuxServer-Thelounge
services:
  app:
    image: linuxserver/thelounge:nightly-version-ae9d312b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/thelounge/'
  tagline:
    en_us: (a Fork Of Shoutirc) Is A Web Irc Client That You Host On Your Own Server.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/community-templates/master/lsiocommunity/img/shout-icon.png
  thumbnail: https://raw.githubusercontent.com/thelounge/thelounge/master/client/img/logo-vertical-transparent-bg.svg?sanitize=true
  title:
    en_us: Thelounge
  category: LinuxServer.io
  port_map: '9000'
