name: LinuxServer-Firefox
services:
  app:
    image: linuxserver/firefox:114.0.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/firefox/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/firefox/'
  tagline:
    en_us: Browser, Also Known As Mozilla Firefox Or Simply Firefox, Is A Free And Open-source Web Browser Developed By The Mozilla Foundation And Its Subsidiary, The Mozilla Corporation. Firefox Uses The Gecko Layout Engine To Render Web Pages, Which Implements Current And Anticipated Web Standards.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
  title:
    en_us: Firefox
  category: LinuxServer.io
  port_map: '3000'
