name: LinuxServer-Libreoffice
services:
  app:
    image: linuxserver/libreoffice:7.5.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/libreoffice/'
  tagline:
    en_us: A Free And Powerful Office Suite, And A Successor To Openoffice.org (commonly Known As Openoffice). Its Clean Interface And Feature-rich Tools Help You Unleash Your Creativity And Enhance Your Productivity.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/libreoffice-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/libreoffice-logo.png
  title:
    en_us: Libreoffice
  category: LinuxServer.io
  port_map: '3000'
