name: LinuxServer-Apprise-api
services:
  app:
    image: linuxserver/apprise-api:0.9.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Where config is stored.
      ports:
        - container: '8000'
          description:
            en_us: Port for apprise's interface and API.
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/apprise-api/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/apprise-api'
  tagline:
    en_us: Takes Advantage Of apprise Through Your Network With A User-friendly Api. * Send Notifications To More Then 65+ Services. * An Incredibly Lightweight Gateway To Apprise. * A Production Ready Micro-service At Your Disposal. Apprise Api Was Designed To Easily Fit Into Existing (and New) Eco-systems That Are Looking For A Simple Notification Solution.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/apprise-api.png
  thumbnail: https://raw.githubusercontent.com/caronc/apprise-api/master/apprise_api/static/logo.png
  title:
    en_us: Apprise Api
  category: LinuxServer.io
  port_map: '8000'
