name: LinuxServer-Quassel-core
services:
  app:
    image: linuxserver/quassel-core:0.14.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: RUN_OPTS
          description:
            en_us: Custom CLI options for Quassel
    ports:
      - target: 4242
        published: 4242
        protocol: tcp
      - target: 113
        published: 10113
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/quassel-core/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/quassel-core/'
  tagline:
    en_us: A Modern, Cross-platform, Distributed Irc Client, Meaning That One (or Multiple) Client(s) Can Attach To And Detach From A Central Core. This Container Handles The Irc Connection (quasselcore) And Requires A Desktop Client (quasselclient) To Be Used And Configured. It Is Designed To Be Always On And Will Keep Your Identity Present In Irc Even When Your Clients Cannot Be Online. Backlog (history) Is Downloaded By Your Client Upon Reconnection Allowing Infinite Scrollback Through Time.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/quassel-core-icon.png
  thumbnail: http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/256/Apps-quassel-icon.png
  title:
    en_us: Quassel Core
  category: LinuxServer.io
