name: LinuxServer-Minetest
services:
  app:
    image: linuxserver/minetest:5.7.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CLI_ARGS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: CLI_ARGS
          description:
            en_us: Optionally specify any CLI variables you want to launch the app with
      volumes:
        - container: /config/.minetest
          description:
            en_us: 'Container Path: /config/.minetest'
      ports:
        - container: '30000'
          description:
            en_us: 'Container Port: 30000'
    ports:
      - target: 30000
        published: 30000
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/minetest/config/.minetest
        target: /config/.minetest
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/minetest/'
  tagline:
    en_us: (server) Is A Near-infinite-world Block Sandbox Game And A Game Engine, Inspired By Infiniminer, Minecraft, And The Like.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/beta-templates/master/lsiodev/img/minetest-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/beta-templates/master/lsiodev/img/minetest-icon.png
  title:
    en_us: Minetest
  category: LinuxServer.io
