name: LinuxServer-Ubooquity
services:
  app:
    image: linuxserver/ubooquity:2.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MAXMEM: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MAXMEM
          description:
            en_us: 'To set the maximum memory. ( ex: set ''1024'' for 1GB )'
    ports:
      - target: 2202
        published: 2202
        protocol: tcp
      - target: 2203
        published: 2203
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ubooquity/config
        target: /config
      - type: bind
        source: /DATA/AppData/ubooquity/books
        target: /books
      - type: bind
        source: /DATA/AppData/ubooquity/comics
        target: /comics
      - type: bind
        source: /DATA/AppData/ubooquity/files
        target: /files
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/ubooquity/'
  tagline:
    en_us: A Free, Lightweight And Easy-to-use Home Server For Your Comics And Ebooks. Use It To Access Your Files From Anywhere, With A Tablet, An E-reader, A Phone Or A Computer.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ubooquity-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ubooquity-banner.png
  title:
    en_us: Ubooquity
  category: LinuxServer.io
