name: LinuxServer-Nzbhydra2
services:
  app:
    image: linuxserver/nzbhydra2:5.1.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 5076
        published: 5076
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nzbhydra2/config
        target: /config
      - type: bind
        source: /DATA/AppData/nzbhydra2/downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/nzbhydra2/'
  tagline:
    en_us: 'A Meta Search Application For Nzb Indexers, The ''spiritual Successor'' To Nzbmegasearch, And An Evolution Of The Original Application nzbhydra. It Provides Easy Access To A Number Of Raw And Newznab Based Indexers. The Application Nzbhydra 2 Is Replacing Nzbhydra 1 And Supports Migrating From V1. Be Wary That There May Be Some Compatibility Issues For Those Migrating From V1 To V2, So Ensure You Back Up Your Old Configuration Before Moving Over To The New Version. note: The Last Version That Supports Migration Is linuxserver/nzbhydra2:v2.10.2-ls49'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
  title:
    en_us: Nzbhydra2
  category: LinuxServer.io
  port_map: '5076'
