name: LinuxServer-Xbackbone
services:
  app:
    image: linuxserver/xbackbone:3.6.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Database and xbackbone configs
      ports:
        - container: '80'
          description:
            en_us: The port for the xbackbone webinterface
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xbackbone/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/xbackbone'
  tagline:
    en_us: A Simple, Self-hosted, Lightweight Php File Manager That Support The Instant Sharing Tool Sharex And *nix Systems. It Supports Uploading And Displaying Images, Gif, Video, Code, Formatted Text, And File Downloading And Uploading. Also Have A Web Ui With Multi User Management, Past Uploads History And Search Support.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xbackbone-logo.png
  thumbnail: https://raw.githubusercontent.com/SergiX44/XBackBone/master/docs/img/xbackbone.png
  title:
    en_us: Xbackbone
  category: LinuxServer.io
  port_map: '80'
