name: LinuxServer-Heimdall
services:
  app:
    image: linuxserver/heimdall:undefined
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: appdata location
      ports:
        - container: '80'
          description:
            en_us: Port for http access
        - container: '443'
          description:
            en_us: Port for https access
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/heimdall/'
  tagline:
    en_us: A Way To Organise All Those Links To Your Most Used Web Sites And Web Applications In A Simple Way. Simplicity Is The Key To Heimdall. Why Not Use It As Your Browser Start Page? It Even Has The Ability To Include A Search Bar Using Either Google, Bing Or Duckduckgo.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/heimdall-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/heimdall-banner.png
  title:
    en_us: Heimdall
  category: LinuxServer.io
  port_map: '80'
