name: LinuxServer-Ldap-auth
services:
  app:
    image: linuxserver/ldap-auth:3.4.3
    restart: unless-stopped
    environment:
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    x-casaos:
      envs:
        - container: FERNETKEY
          description:
            en_us: Optionally define a custom valid fernet key (only needed if container is frequently recreated, or if using multi-node setups, invalidating previous authentications)
        - container: CERTFILE
          description:
            en_us: Optionally point this to a certificate file to enable HTTP over SSL (HTTPS) for the ldap auth daemon
        - container: KEYFILE
          description:
            en_us: Optionally point this to the private key file, matching the certificate file referred to in CERTFILE
      ports:
        - container: '8888'
          description:
            en_us: LDAP auth daemon port
        - container: '9000'
          description:
            en_us: LDAP login page port
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/ldap-auth/'
  tagline:
    en_us: Software Is For Authenticating Users Who Request Protected Resources From Servers Proxied By Nginx. It Includes A Daemon (ldap-auth) That Communicates With An Authentication Server, And A Webserver Daemon That Generates An Authentication Cookie Based On The User’s Credentials. The Daemons Are Written In Python For Use With A Lightweight Directory Access Protocol (ldap) Authentication Server (openldap Or Microsoft Windows Active Directory 2003 And 2012).
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ldap-auth-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ldap-auth-logo.png
  title:
    en_us: Ldap Auth
  category: LinuxServer.io
