name: LinuxServer-Calibre
services:
  app:
    image: linuxserver/calibre:4.23.0-v4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CLI_ARGS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: PASSWORD
          description:
            en_us: Optionally set a password for the gui.
        - container: CLI_ARGS
          description:
            en_us: Optionally pass cli start arguments to calibre.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '8080'
          description:
            en_us: GUI Port - Default 8080
        - container: '8081'
          description:
            en_us: Webserver Port - Default 8081
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/calibre/'
  tagline:
    en_us: A Powerful And Easy To Use E-book Manager. Users Say It's Outstanding And A Must-have. It'll Allow You To Do Nearly Everything And It Takes Things A Step Beyond Normal E-book Software. It's Also Completely Free And Open Source And Great For Both Casual Users And Computer Experts.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-icon.png
  thumbnail: https://github.com/kovidgoyal/calibre/raw/master/resources/images/lt.png
  title:
    en_us: Calibre
  category: LinuxServer.io
  port_map: '8080'
