name: LinuxServer-Lazylibrarian
services:
  app:
    image: linuxserver/lazylibrarian:version-f066b525
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DOCKER_MODS
          description:
            en_us: Allows additional functionality to be added, e.g. the Calibredb import program (optional, more info below)
    ports:
      - target: 5299
        published: 5299
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lazylibrarian/config
        target: /config
      - type: bind
        source: /DATA/AppData/lazylibrarian/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/lazylibrarian/books
        target: /books
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/lazylibrarian/'
  tagline:
    en_us: A Program To Follow Authors And Grab Metadata For All Your Digital Reading Needs. It Uses A Combination Of Goodreads Librarything And Optionally Googlebooks As Sources For Author Info And Book Info. This Container Is Based On The Dobytang Fork.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lazylibrarian-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lazylibrarian-icon.png
  title:
    en_us: Lazylibrarian
  category: LinuxServer.io
  port_map: '5299'
